runtime: nodejs
env: flex

handlers:
- url: /.*
  static_files: build/index.html
  upload: build/index.html
- url: /(.*\.(js|css|png|jpg|svg|ico|json))
  static_files: build/\1
  upload: build/.*\.(js|css|png|jpg|svg|ico|json)
