jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (other steps)
      - name: Setup Google Cloud SDK        
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true 

      - name: Activate Service Account 
        run: |-
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ./key.json 
          gcloud auth activate-service-account --key-file ./key.json 

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2  
