name: Deploy to Google App Engine

on:
  push:
    branches: [ main ]  # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Google Cloud SDK        
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true 

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2  

